### ISSUE TITLE
symbolic link identification

### ISSUE THREAD

**Issue by alpheratz0** [phillbush/xfiles#13]
as it is now you can't differentiate a file/directory from a symbolic link to a
file/directory, thats because the use of `stat(2)` which will follow the symbolic link,
maybe add an extra flag to the mode, something like `MODE_LINK` and use `lstat(2)`
to set that, which later can be used to draw an arrow or something similar at the
bottom right corner of the icon if it is a symlink, you know better the source so I'm
sure that you can think of a better way to do it :D

**Comment by phillbush** [comment]
A `"dl"` on the `FILE_ICONS` environment variable now matches a link to a directory.

I've also added a new .xpm icon for link to directory:
![scrot-2023-01-06-214628](https://user-images.githubusercontent.com/63266536/211123135-b5339d41-b7bb-4937-88fc-59615d0e4af8.png)

**Comment by alpheratz0** [comment]
> A `"dl"` on the `FILE_ICONS` environment variable now matches a link to a directory.
> 
> I've also added a new .xpm icon for link to directory (it need to be configured manually, tho): ![scrot-2023-01-06-214628](https://user-images.githubusercontent.com/63266536/211123135-b5339d41-b7bb-4937-88fc-59615d0e4af8.png)

Nice work!!!!!!!!! Thanks!
