### ISSUE TITLE
Feature Request: Make Thumbnails Follow Sym Links

### ISSUE THREAD

**Issue by Randalix** [phillbush/xfiles#23]
The thumbnail path could follow system links. So thumbnails do not need to be regenerated.

I'm imagining of a workflow where we can use symlinks to make virtual folders, but do not regenerate thumbnails.

Examples are:
A file search presents its result in a "virtual folders"  with the found files linked in it.
"Virtual folders" based on file tags.
 
The follow system links feature could be enabled with a flag.

**Comment by phillbush** [comment]
That's a nice feature, which also saves space.
Implemented on the last commit.
There's no need to save two files for the same thumbnail.
