### ISSUE TITLE
contextcmd is not run with absolute path of file

### ISSUE THREAD

**Issue by wael444** [phillbush/xfiles#24]
title.
for example, xfilesctl can run with file `.profile` as an argument, but that won't work due to PWD. is this intentional because xfilesctl will be spawned in the pwd of the xfiles gui?

**Comment by phillbush** [comment]
> is this intentional because xfilesctl will be spawned in the pwd of the xfiles gui?

Yeah, `xfilesctl` is spawned with its current working directory as the directory where the selected files are at.
So there's no need to give the absolute paths, as they are already relative to where the script is invoked.

That was done in [this commit](https://github.com/phillbush/xfiles/commit/80c849afa4b742047b28a8195deed4f8aaa4510b).

If you want the absolute paths in the script, you can prefix the arguments with `$PWD`.
(Or the commit can be reverted, if proved necessary to have the absolute paths instead).

**Comment by wael444** [comment]
it 100% should be absolute paths instead, this can be unsafe..

**Comment by phillbush** [comment]
Done.
