### ISSUE TITLE
selection rectangle position stays/renders in drag and drop & drop-ask is not provided with target

### ISSUE THREAD

**Issue by wael444** [phillbush/xfiles#25]
```
drop-ask /home/wael/.profile
```

**Comment by wael444** [comment]
https://user-images.githubusercontent.com/47404953/212342650-0e6f14ab-e121-410a-b2c9-afe4f7bc930e.mp4

**Comment by phillbush** [comment]
I could not reproduce the error here, but I found the lines of code that could be causing it for you.
I think it should be fixed now.
