### ISSUE TITLE
two selection bugs

### ISSUE THREAD

**Issue by alpheratz0** [phillbush/xfiles#28]
* part of the selection rectangle is not rendered (I think that the problem is [here](https://github.com/phillbush/xfiles/blob/master/widget.c#L701))
* the last item is selected but it should not

A video is worth a thousand images...

https://user-images.githubusercontent.com/93066036/212435316-7d0a9126-f9cd-4d49-889e-4ae6cf7fc2ef.mp4

**Comment by phillbush** [comment]
Hi @alpheratz0

The last two commits fix each bug.

**Comment by phillbush** [comment]
Btw, I see you're using transparency.
Do the icons and text are transparent as well or only the background?
And how are you achieving transparency?

**Comment by alpheratz0** [comment]
> Btw, I see you're using transparency.
> Do the icons and text are transparent as well or only the background?

At first I thought it was only the background, but by setting the opacity to a lower
value you can see that also the icons and text gets transparent.
![screenshot](https://user-images.githubusercontent.com/93066036/212442225-9f3d38dc-40c6-4a23-9c0b-1f3d66f3560b.png)

> And how are you achieving transparency?

Picom, why?

**Comment by phillbush** [comment]
That's because XFiles uses the default X depth and X drawing routines, which does not use alpha channel.
I'm working on a new commit that makes transparency work only on the background.

**Comment by phillbush** [comment]
Ok, I added a `XFiles.opacity` X resource.
It is a float number from `0.0` (full transparent) to `1.0` (full opaque).

![opacity](https://user-images.githubusercontent.com/63266536/212449565-51a97b93-62cc-4a3c-ab2b-6f899305e8a8.png)

It required considerable changing on the X drawing code... I hope I have not broken anything...

**Comment by phillbush** [comment]
It still needs a compositor for the transparency to work, but you now need to configure the opacity in XFiles itself (via X resources) rather than on picom.
