### ISSUE TITLE
Virtual root

### ISSUE THREAD

**Issue by grimnight** [phillbush/xfiles#29]
The ability to limit navigation to a specific folder and its subfolders, like in [xplr].

[xplr]: https://xplr.stck.me/post/47888/xplr-v0-20-0-what-s-new

**Comment by phillbush** [comment]
I don't know xplr or its features.  
I'm going to check it and see what can be imported into XFiles.

**Comment by phillbush** [comment]
This feature can be implemented.
However, I'm not convinced on its usefulness.

If the user can enable and disable this *virtual root* feature at will, what does the user gain by limiting himself to a subtree of the file system?

If the gained utility is to quickly move to a project's root tree, you can add a keybinding into `xfilesctl` (say, `Ctrl-P`) that change the directory to `$PROJECT_ROOT` and then call `PROJECT_ROOT="$PWD" xfiles` to quickly move to the current directory with `Ctrl-P`.
