### ISSUE TITLE
Segmentation fault when selecting a broken symlink

### ISSUE THREAD

**Issue by tdukv** [phillbush/xfiles#36]
Unlike #34 opening the directory is fine, but clicking on the file or moving to it with the arrow keys causes segmentation fault.

**Comment by apprehensions** [comment]
i don't get a seg fault, xfiles immediately tries to forward it to my mime handler program.

**Comment by phillbush** [comment]
[Sorry, I fixed the issue but linked to #34 ... here's what I posted there]

Indeed, the bug was introduced by the status bar commit.
The status bar needs to draw the file's status created by xfiles (size, owner and time), which is NULL for broken links.
The last commit handles NULL status lines.
