### ISSUE TITLE
Pahtes seem not to be send to XFILES_CONTEXTCMD

### ISSUE THREAD

**Issue by Randalix** [phillbush/xfiles#4]
To test the functionality of XFILES_CONTEXTCMD I've created this script:
```
#!/usr/bin/sh

notify-send "triggered"
echo "$@"
notify-send "$@"

```
When I rightclick in xfiles the notify-send command gets triggered, but the pathes seem not to be there.
Am I missing something?

**Comment by phillbush** [comment]
Have you selected a file or right-clicked on a file?
The context command is called with the selected files as arguments, when there's no selected files, the argument list is empty.

There's also two issues happening here:

>`echo "$@"`

xfiles redirects the stdout of the invoked command to /dev/null, you can try echoing to stderr or into a file to check whether it is working.

>`notify-send "$@"`

If you have more than two files selected, the script will be called with more than two arguments, and notify-send only likes two or less arguments.

```
$ notify-send a b c d
Invalid number of options.
```
