### ISSUE TITLE
Spawned terminals override umask to 0000.

### ISSUE THREAD

**Issue by tdukv** [phillbush/xfiles#41]
Terminals spawned from XFiles inherit an umask of 0000, regardless of what it had been set previously.
Tested also with an original xfilesctl.

**Comment by phillbush** [comment]
Hi, I copied the `mkpath` algorithm from [OpenBSD's mkdir](https://github.com/openbsd/src/blob/master/bin/mkdir/mkdir.c#L127) which uses `umask(2)` to get the current umask. Now i'm using hardcoded modes; in particular, the thumbnail directory is created with mode `0700` so only the owner user can write/read/cd it.

Thanks for reporting the issue.
