### ISSUE TITLE
Xfiles crash when launched trough xclickroot

### ISSUE THREAD

**Issue by wesbluemarine** [phillbush/xfiles#44]
Launching xfiles with middle desktop click (xclickroot -m xfiles) causes xfiles crash every time right click menu (pmenu) is released.

Error message:
`xfiles: waitpid: No child processes`

**Comment by aspizu** [comment]
can reproduce, doesn't happen when xfiles is launched from a terminal.

**Comment by emanuele6** [comment]
By the way, until the issue is fixed, on GNU/Linux, you can work around the problem without patching using GNU `env`:
```sh
xclickroot -m env --default-signal=CHLD xfiles 
```

**Comment by aspizu** [comment]
Thank you.
