### ISSUE TITLE
feature request: hidden files configurable via variables

### ISSUE THREAD

**Issue by wael444** [phillbush/xfiles#5]
self explanatory? i don't understand xfile's functions yet so i cant really see why this is the case.

**Comment by wael444** [comment]
nvm i see now

**Comment by wael444** [comment]
```c
		case 'a':
			hide = 0;
			break;
```
IMO this should be configured by variables/Xresources as well.

**Comment by phillbush** [comment]
The "show all mode" to show hidden files can be set just like in `ls(1)` with the `-a` option:

```
$ xfiles -a
```

**Comment by wael444** [comment]
i know!! but what about an option so i dont have to make a bin script override for a flag
