### ISSUE TITLE
Not compiling on Linux

### ISSUE THREAD

**Issue by tdukv** [phillbush/xfiles#53]
After commit 30e2079 xfiles does not compile:

`
$ make
cc -std=c99 -pedantic -D_POSIX_C_SOURCE=200809L -D_BSD_SOURCE -D_DEFAULT_SOURCE -I/usr/local/include -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/X11R6/include/freetype2   -o xfiles.o -c xfiles.c
xfiles.c: In function 'checkicon':
xfiles.c:343:25: error: 'FNM_CASEFOLD' undeclared (first use in this function)
  343 |                 flags = FNM_CASEFOLD | FNM_PATHNAME;
      |                         ^~~~~~~~~~~~
xfiles.c:343:25: note: each undeclared identifier is reported only once for each function it appears in
xfiles.c: In function 'runxfilesctl':
xfiles.c:659:13: warning: implicit declaration of function 'pipe2'; did you mean 'pipe'? [-Wimplicit-function-declaration]
  659 |         if (pipe2(pipefds, O_CLOEXEC) == RETURN_FAILURE)
      |             ^~~~~
      |             pipe
make: *** [Makefile:74: xfiles.o] Error 1
`

**Comment by phillbush** [comment]
Commit 97e8a90 should fix that.

I do not have a Linux around to test it right now, but according to the
manuals it was only a matter of using the right feature_test_macros(7).

**Comment by tdukv** [comment]
Tried the #52 PR and it fixes the compile issue.
97e8a90 still has an INFTIM undefined error.

**Comment by phillbush** [comment]
Fixed again by ecf8e4b
I am gonna check compilation on Linux tomorrow if it complains of any other undefined symbols.
